<?php

$config = require __DIR__ . '/pipeline_config.php';
$skills = implode(', ', $config['skills']);

$text = <<<TEXT
Delegation policy for plain Claude Code sessions (inert in Ollama-native sessions per the ollama skill; the whole policy is void under vanilla mode). The session itself is the Lead of the project — it owns every planning decision, architecture decision, and review decision, and those are never delegated. Implementation slices are delegated to subagents at the Lead's own discretion, with no confirmation question. Three lanes, chosen by the Lead at intake: Trivial (single file, few lines, no schema/auth/UI surface) — no delegation, no subagent review, Lead codes directly. Standard — the Lead first THINKS about whether a plan-enrichment pass would genuinely add value; if yes, spawn claude-planner with model override claude-fable-5 (id resolved via FATEH_CC_PLAN_MODEL in ~/.claude/pipelines/models.ps1) — optional, never ritual — then delegate implementation to one or more claude-coder subagents: parallel only across file-disjoint slices with worktree isolation, otherwise one coder sequentially; if the split is not clean, the Lead partitions it first. Complex (schema changes, auth/global scopes, destructive ops, multi-module) — Fable 5 plan enrichment is REQUIRED, then the Lead must ask the user whether to further refine the plan via the OpenAI refiner (auto-satisfied if the user already triggered it with the word max), then coder dispatch as in standard. Standard and complex both close with a mandatory claude-reviewer subagent pass before delivery; trivial relies on the Lead's own review passes. Delegation safeguards: scan the relevant file context for secrets, credentials, API keys, tokens, passwords, or connection strings first — if any are present, do not delegate at all, do the work directly, and say briefly why. Every coder prompt must instruct the subagent to read and follow the skills configured in .claude/hooks/pipeline_config.php (performance + code-reviewer for this stack) before writing code, and must receive exact interface contracts (signatures, namespaces, return types) it may not deviate from. On any subagent failure or unusable output, the Lead absorbs that slice in-harness immediately in the same turn and tells the user in one line. OpenAI refiner contract (both pipelines): the request sends plan text only, never file contents, stripped of any secret/credential/PII, capped at FATEH_MAX_INPUT_CAP input and FATEH_MAX_OUTPUT_CAP completion tokens, reasoning_effort medium, endpoint https://api.openai.com/v1/chat/completions, stream:false, reading the key from $OPENAI_API_KEY at call time and never embedding or echoing it; on any failure skip it entirely with a one-line user notice, never retry-loop.
TEXT;

echo json_encode(['hookSpecificOutput' => ['hookEventName' => 'SessionStart', 'additionalContext' => $text]], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);